server:
  port: 8080

spring:
  application:
    name: api-gateway

  codec:
    max-in-memory-size: 10MB

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/user

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**

        - id: post-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/posts/**
          filters:
            - name: CircuitBreaker
              args:
                name: postServiceCB
                fallbackUri: forward:/fallback/post
        - id: follow-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/follow/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG


security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

resilience4j:
  circuitbreaker:
    instances:
      userServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      postServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
